=== SM2XML/XML_Project_SM_Team/public/students.dtd
<!ELEMENT students (student*)>
<!ELEMENT student (CNE, FirstName, LastName, DateOfBirth, ClassName, Phone*, Email+)>
<!ELEMENT CNE (#PCDATA)>
<!ELEMENT FirstName (#PCDATA)>
<!ELEMENT LastName (#PCDATA)>
<!ELEMENT DateOfBirth (#PCDATA)>
<!ELEMENT ClassName (#PCDATA)>
<!ELEMENT Phone (#PCDATA)>
<!ELEMENT Email (#PCDATA)>

=== SM2XML/XML_Project_SM_Team/public/Ginf2_Students.xml
<?xml version="1.0"?>
<!DOCTYPE students SYSTEM "students.dtd">
<students>
    <student>
        <CNE>17003791</CNE>
        <FirstName>Taha</FirstName>
        <LastName>Kherraf</LastName>
        <DateOfBirth>01/01/1999</DateOfBirth>
        <ClassName>GINF2</ClassName>
        <Phone>0600000000</Phone>
        <Email>taha.kherraf@etu.uae.ac.ma</Email>
    </student>
    <student>
        <CNE>1502397848</CNE>
        <FirstName>Salma</FirstName>
        <LastName>El Aakkouchi</LastName>
        <DateOfBirth>02/03/1999</DateOfBirth>
        <ClassName>GINF2</ClassName>
        <Phone>638373746</Phone>
        <Email>salma.elaakkouchi@gmail.com</Email>
    </student>
    <student>
        <CNE>17004437</CNE>
        <FirstName>Ikrame</FirstName>
        <LastName>Sahel</LastName>
        <DateOfBirth>01/02/1999</DateOfBirth>
        <ClassName>GINF2</ClassName>
        <Phone>0600000001</Phone>
        <Email>ikrame.sahel@etu.uae.ac.ma</Email>
    </student>
    <student>
        <CNE>17003812</CNE>
        <FirstName>Mohamed</FirstName>
        <LastName>Jadar</LastName>
        <DateOfBirth>01/03/1999</DateOfBirth>
        <ClassName>GINF2</ClassName>
        <Phone>0600000002</Phone>
        <Email>mohamed.jadar@etu.uae.ac.ma</Email>
    </student>
    <student>
        <CNE>17004448</CNE>
        <FirstName>Souhaib</FirstName>
        <LastName>Essarrhini</LastName>
        <DateOfBirth>02/03/1999</DateOfBirth>
        <ClassName>GINF2</ClassName>
        <Phone>0600000003</Phone>
        <Email>souhaib.essarrhini@etu.uae.ac.ma</Email>
    </student>
    <student>
        <CNE>17004445</CNE>
        <FirstName>KHAWLA</FirstName>
        <LastName>ADRAOUI</LastName>
        <DateOfBirth>03/03/1999</DateOfBirth>
        <ClassName>GINF2</ClassName>
        <Phone>0600000004</Phone>
        <Email>khawla.adraoui@etu.uae.ac.ma</Email>
    </student>
    <student>
        <CNE>17005951</CNE>
        <FirstName>Mohamed</FirstName>
        <LastName>Ahmadoun</LastName>
        <DateOfBirth>04/03/1999</DateOfBirth>
        <ClassName>GINF2</ClassName>
        <Phone>0600000005</Phone>
        <Email>mohamed.ahmadoun@etu.uae.ac.ma</Email>
    </student>
    <student>
        <CNE>17003373</CNE>
        <FirstName>CHAIMAE</FirstName>
        <LastName>AMEZIANE</LastName>
        <DateOfBirth>05/03/1999</DateOfBirth>
        <ClassName>GINF2</ClassName>
        <Phone>0600000006</Phone>
        <Email>chaimae.ameziane@etu.uae.ac.ma</Email>
    </student>
    <student>
        <CNE>16000421</CNE>
        <FirstName>Mohamed</FirstName>
        <LastName>Ben Taher</LastName>
        <DateOfBirth>06/03/1999</DateOfBirth>
        <ClassName>GINF2</ClassName>
        <Phone>0600000007</Phone>
        <Email>mohamed.bentaher@etu.uae.ac.ma</Email>
    </student>
    <student>
        <CNE>17006268</CNE>
        <FirstName>Adnane</FirstName>
        <LastName>BENABDELLAH</LastName>
        <DateOfBirth>07/03/1999</DateOfBirth>
        <ClassName>GINF2</ClassName>
        <Phone>0600000008</Phone>
        <Email>adnane.benabdellah@etu.uae.ac.ma</Email>
    </student>
    <student>
        <CNE>17003531</CNE>
        <FirstName>Iness</FirstName>
        <LastName>Bouabid</LastName>
        <DateOfBirth>08/03/1999</DateOfBirth>
        <ClassName>GINF2</ClassName>
        <Phone>0600000009</Phone>
        <Email>iness.bouabid@etu.uae.ac.ma</Email>
    </student>
    <student>
        <CNE>17003833</CNE>
        <FirstName>Youssef</FirstName>
        <LastName>Charfi</LastName>
        <DateOfBirth>09/03/1999</DateOfBirth>
        <ClassName>GINF2</ClassName>
        <Phone>0600000010</Phone>
        <Email>youssef.charfi@etu.uae.ac.ma</Email>
    </student>
    <student>
        <CNE>17005894</CNE>
        <FirstName>mohammed said</FirstName>
        <LastName>dahchar</LastName>
        <DateOfBirth>10/03/1999</DateOfBirth>
        <ClassName>GINF2</ClassName>
        <Phone>0600000011</Phone>
        <Email>mohammedsaid.dahchar@etu.uae.ac.com</Email>
    </student>
    <student>
        <CNE>17003240</CNE>
        <FirstName>hamza</FirstName>
        <LastName>el azizi</LastName>
        <DateOfBirth>11/03/1999</DateOfBirth>
        <ClassName>GINF2</ClassName>
        <Phone>0600000012</Phone>
        <Email>hamza.elazizi@etu.uae.ac.ma</Email>
    </student>
    <student>
        <CNE>17004484</CNE>
        <FirstName>Mohamed amine</FirstName>
        <LastName>El haddaji</LastName>
        <DateOfBirth>12/03/1999</DateOfBirth>
        <ClassName>GINF2</ClassName>
        <Phone>0600000013</Phone>
        <Email>Mohamedamine.elhaddaji@etu.uae.ac.ma</Email>
    </student>
    <student>
        <CNE>17007212</CNE>
        <FirstName>Mouad</FirstName>
        <LastName>El Mamoune</LastName>
        <DateOfBirth>13/03/1999</DateOfBirth>
        <ClassName>GINF2</ClassName>
        <Phone>0600000014</Phone>
        <Email>mouad.elmamoune@etu.uae.ac.ma</Email>
    </student>
    <student>
        <CNE>17007213</CNE>
        <FirstName>Issam</FirstName>
        <LastName>El Mansouri</LastName>
        <DateOfBirth>14/03/1999</DateOfBirth>
        <ClassName>GINF2</ClassName>
        <Phone>0600000015</Phone>
        <Email>issam.elmansouri@etu.uae.ac.ma</Email>
    </student>
    <student>
        <CNE>17003312</CNE>
        <FirstName>YASSINE</FirstName>
        <LastName>EL MOUSTACHIR</LastName>
        <DateOfBirth>15/03/1999</DateOfBirth>
        <ClassName>GINF2</ClassName>
        <Phone>0600000016</Phone>
        <Email>yassine.elmoustachir@etu.uae.ac.ma</Email>
    </student>
    <student>
        <CNE>17003435</CNE>
        <FirstName>Mohammad elamine</FirstName>
        <LastName>Elkhayyat</LastName>
        <DateOfBirth>01/04/1999</DateOfBirth>
        <ClassName>GINF2</ClassName>
        <Phone>0600000017</Phone>
        <Email>mohammadelamine.elkhayyat@etu.uae.ac.ma</Email>
    </student>
    <student>
        <CNE>17003902</CNE>
        <FirstName>Youssef</FirstName>
        <LastName>Falaki</LastName>
        <DateOfBirth>02/04/1999</DateOfBirth>
        <ClassName>GINF2</ClassName>
        <Phone>0600000018</Phone>
        <Email>Youssef.falaki@etu.uae.ac.ma</Email>
    </student>
    <student>
        <CNE>17004052</CNE>
        <FirstName>ADNANE</FirstName>
        <LastName>ACHAHBAR</LastName>
        <DateOfBirth>03/04/1999</DateOfBirth>
        <ClassName>GINF2</ClassName>
        <Phone>0600000019</Phone>
        <Email>adnane.achahbar@etu.uae.ac.ma</Email>
    </student>
    <student>
        <CNE>17004621</CNE>
        <FirstName>Youssef</FirstName>
        <LastName>LAIDOUNI</LastName>
        <DateOfBirth>04/04/1999</DateOfBirth>
        <ClassName>GINF2</ClassName>
        <Phone>0600000020</Phone>
        <Email>youssef.laidouni@etu.uae.ac.ma</Email>
    </student>
    <student>
        <CNE>17003906</CNE>
        <FirstName>Imane</FirstName>
        <LastName>Malawi</LastName>
        <DateOfBirth>05/04/1999</DateOfBirth>
        <ClassName>GINF2</ClassName>
        <Phone>0600000021</Phone>
        <Email>Imane.malawi@etu.uae.ac.ma</Email>
    </student>
    <student>
        <CNE>17004463</CNE>
        <FirstName>El Mehdi</FirstName>
        <LastName>Mansour</LastName>
        <DateOfBirth>06/04/1999</DateOfBirth>
        <ClassName>GINF2</ClassName>
        <Phone>0600000022</Phone>
        <Email>elmehdi.mansour@etu.uae.ac.ma</Email>
    </student>
    <student>
        <CNE>17004490</CNE>
        <FirstName>ILIAS</FirstName>
        <LastName>MAZTAOUI</LastName>
        <DateOfBirth>07/04/1999</DateOfBirth>
        <ClassName>GINF2</ClassName>
        <Phone>0600000023</Phone>
        <Email>ilias.maztaoui@etu.uae.ac.ma</Email>
    </student>
    <student>
        <CNE>17008009</CNE>
        <FirstName>Salima</FirstName>
        <LastName>Noufel</LastName>
        <DateOfBirth>08/04/1999</DateOfBirth>
        <ClassName>GINF2</ClassName>
        <Phone>0600000024</Phone>
        <Email>salima.noufel@etu.uae.ac.ma</Email>
    </student>
    <student>
        <CNE>17006208</CNE>
        <FirstName>HAJAR</FirstName>
        <LastName>SERRAD</LastName>
        <DateOfBirth>09/04/1999</DateOfBirth>
        <ClassName>GINF2</ClassName>
        <Phone>0600000025</Phone>
        <Email>hajar.serrad@etu.uae.ac.ma</Email>
    </student>
    <student>
        <CNE>17003768</CNE>
        <FirstName>YAZID</FirstName>
        <LastName>ZALAI</LastName>
        <DateOfBirth>10/04/1999</DateOfBirth>
        <ClassName>GINF2</ClassName>
        <Phone>0600000026</Phone>
        <Email>yazid.zalai@etu.uae.ac.ma</Email>
    </student>
    <student>
        <CNE>17009146</CNE>
        <FirstName>Ebenezer Stephane</FirstName>
        <LastName>Tolly</LastName>
        <DateOfBirth>11/04/1999</DateOfBirth>
        <ClassName>GINF2</ClassName>
        <Phone>0600000027</Phone>
        <Email>stephaneafolabi.tollyebenezer@etu.uae.ac.ma</Email>
    </student>
    <student>
        <CNE>17008402</CNE>
        <FirstName>HERMAN JOEL</FirstName>
        <LastName>TATANI BOUTCHUENG</LastName>
        <DateOfBirth>12/04/1999</DateOfBirth>
        <ClassName>GINF2</ClassName>
        <Phone>0600000028</Phone>
        <Email>hermanjoel.tataniboutchueng@etu.uae.ac.ma</Email>
    </student>
    <student>
        <CNE>17008409</CNE>
        <FirstName>Joseph amile Boris</FirstName>
        <LastName>NGAN MINTAMAK</LastName>
        <DateOfBirth>05/05/1999</DateOfBirth>
        <ClassName>GINF2</ClassName>
        <Phone>0600000029</Phone>
        <Email>josephemileboris.nganmintamak@etu.uae.ac.ma</Email>
    </student>
    <student>
        <CNE>17004661</CNE>
        <FirstName>Maria</FirstName>
        <LastName>aissa</LastName>
        <DateOfBirth>06/05/1999</DateOfBirth>
        <ClassName>GINF2</ClassName>
        <Phone>0600000030</Phone>
        <Email>maria.aissa@etu.uae.ac.ma</Email>
    </student>
    <student>
        <CNE>17005996</CNE>
        <FirstName>BASMA</FirstName>
        <LastName>BOUHAL</LastName>
